name: tasklist_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  equatable: ^2.0.5
  firedart: ^0.9.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  meta: ^1.10.0
  mongo_dart: ^0.9.1
  postgres: ^2.6.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
